test: CustomerProject.cpp PreferredProject.cpp RegularProject.cpp main.cpp CustomerProject.hpp PreferredProject.hpp RegularProject.hpp
	g++ CustomerProject.cpp PreferredProject.cpp RegularProject.cpp main.cpp -o test
